version: "3.7"

services:
  db:
    image: mysql:latest
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - ./db-data:/var/lib/kerntrafo_mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=kerntrafo
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 3306:3306
    expose:
      - "3306"
      - "33060"

  app:
    build: .
    container_name: app
    restart: always
    secrets:
      - db-password
    ports:
      - 8000:8000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URI=mysql+pymysql://root:@KTDB2021@db:3306/kerntrafo
    links: 
      - db


 
volumes:
  db-data:
    driver: local
secrets:
  db-password:
    file: db/password.txt
networks:
  backnet:
  frontnet:
